base_url = "https://seniormars.com"
title = "SeniorMars"
description = "A blog about math, extremely niche interests, and a guy having fun."

# settings
theme = "redux"
author = "SeniorMars"
default_language = "en"
build_search_index = true
generate_feeds = true
compile_sass = true
feed_filenames = ["rss.xml"]
taxonomies = [
    { name = "tags", feed = true, paginate_by = 10 } ,
    { name = "authors", feed = true, paginate_by = 10 } ,
]


[search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_json"

[link_checker]
internal_level = "warn"
skip_anchor_prefixes = [
    "https://github.com/",
]

[markdown]
highlight_code = true
render_emoji = true
smart_punctuation = true
highlight_theme = "ayu-dark"
external_links_no_referrer = true
bottom_footnotes = true
extra_syntaxes_and_themes = ["syntaxes"]

[extra]
toc = true
use_cdn = false
comment = false
mermaid = true
mathjax = true
mathjax_extra = true
fancy_code = true
dynamic_note = true
mobile = true
theme = "toggle"
favicon = "/icons/favicon.ico"
favicon_extra = true
repo_url = "https://github.com/SeniorMars/seniormars.com/blob/main/content/"
browser_theme_color = ["#FFFFFF", "#0E1018"]

menu = [
    { name = "/posts", url = "/posts", weight = 1 },
    { name = "/projects", url = "/projects", weight = 2 },
    { name = "/about", url = "/about", weight = 3 },
    { name = "/etc", url = "/etc", weight = 4 },
]

socials = [
    { name = "github", url = "https://github.com/seniormars/", icon = "github" },
    { name = "youtube", url = "https://www.youtube.com/seniormarstries", icon = "youtube" },
    { name = "rss", url = "/rss.xml", icon = "rss" },
]

cards_columns = 3
card_media_height = 200

custom_css = []

[extra.taxonomies]
sort_by = "page_count"         # e.g. name, page_count
reverse = true

[extra.analytics]
enabled = true

[extra.analytics.goatcounter]
user = "seniormars"
